# This is a basic workflow to help you get started with Actions

name: ROS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-melodic:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    container: 
      image: rduweston/ubuntu-ci:melodic
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libasio-dev
    - name: Create catkin workspace
      run: mkdir -p /catkin_ws/src && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - name: Copy code to catkin workspace
      run: cd /catkin_ws/src && git clone -b next https://github.com/westonrobot/ugv_sdk.git
    - name: Run catkin_make
      run: cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make"
